# Generated by Django 4.1.2 on 2022-10-13 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stars", models.PositiveIntegerField()),
                ("review", models.TextField()),
                ("spoilers", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "recomendation",
                    models.CharField(
                        choices=[
                            ("Must Watch", "Must Watch"),
                            ("Should Watch", "Should Watch"),
                            ("Avoid Watch", "Avoid Watch"),
                            ("No Opinion", "No Opinion"),
                        ],
                        default="No Opinion",
                        max_length=50,
                    ),
                ),
                (
                    "movie_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="movies.movie",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
