# Generated by Django 4.1.2 on 2022-10-15 20:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("movie_id", "user_id")},
        ),
    ]
